name: Deploy Cloudflare Pages

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
        env:
          TZ: Asia/Tokyo
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: d8ffa051ff726193056507455bf58eb1
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: bushitsu-web
          directory: out/
          branch: main
